[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
remappings = [  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", 
                "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts", 
                "@aave/core-v3/contracts/=lib/aave-v3-core/contracts/",
                "@forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
