[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
remappings = ["@openzeppelin/contracts-upgradeable=node_modules/@openzeppelin/contracts-upgradeable"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
